version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-here
    restart: unless-stopped
    networks:
      - processing-net

networks:
  processing-net:
    driver: bridge